import React,{useEffect,useRef,useState} from 'react';
import {Compass,Sun,Moon,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,ArrowsOut,Camera,House,Stack,PersonSimpleWalk,Cube,Play,Pause,X,List,Info,Leaf,ArrowCounterClockwise,CaretRight,Eye,Buildings} from '@phosphor-icons/react';
import {createEngine} from './engine';
import {ROOMS,VIEWS,FLOORS} from './plan';
import './styles.css';
export function App(){
 const mount=useRef(null),engine=useRef(null);const [ready,setReady]=useState(false),[error,setError]=useState(''),[floor,setFloor]=useState(-1),[night,setNight]=useState(false),[walk,setWalk]=useState(false),[isolated,setIsolated]=useState(true),[roof,setRoof]=useState(true),[quality,setQuality]=useState('high'),[room,setRoom]=useState(null),[view,setView]=useState('aerial'),[menu,setMenu]=useState(false),[info,setInfo]=useState(false),[tour,setTour]=useState(false),[stats,setStats]=useState({fps:0});
 useEffect(()=>{const t=setTimeout(()=>{try{engine.current=createEngine(mount.current,()=>setReady(true),setStats,setFloor);}catch(e){console.error(e);setError('The 3D viewer could not start. Enable hardware acceleration and try a current Chrome, Edge or Firefox browser. '+e.message);}},80);return()=>{clearTimeout(t);engine.current?.dispose();};},[]);
 function chooseFloor(f){setFloor(f);setRoom(null);setTour(false);setWalk(false);engine.current?.setWalk(false);engine.current?.setFloor(f);setMenu(false);}
 function chooseRoom(r){setRoom(r);setFloor(r.floor);setTour(false);engine.current?.goTo(r,true);setMenu(false);}
 function chooseView(id){const v=VIEWS.find(v=>v.id===id);if(!v)return;setView(id);setTour(false);if(v.night){setNight(true);}engine.current?.goTo(v);if(v.floor===undefined){setFloor(-1);engine.current?.setFloor(-1,false);}setRoom(null);}
 const toggle=(setter,fn,value)=>{setter(value);engine.current?.[fn](value);};
 function keyButton(e,key,v){e.preventDefault();engine.current?.setKey(key,v);if(v)e.currentTarget.setPointerCapture(e.pointerId);}
 return <main className={night?'app night':'app'}>
  <section ref={mount} className="viewport" aria-label="Villa 3D viewport" />
  {(!ready||error)&&<div className="loading" role="status"><House size={40} weight="thin"/><h2>{error?'Viewer unavailable':'Opening your home'}</h2><p>{error||'Preparing the architecture, water and interiors…'}</p></div>}
  <button className="mobile-menu iconbutton" aria-label="Open floor and room navigation" onClick={()=>setMenu(!menu)}><List size={22}/></button>
  <aside className={'sidebar '+(menu?'open':'')}>
   <div className="brand"><span className="brandmark"><Leaf size={29} weight="thin"/></span><div><span className="eyebrow">PRIVATE RESIDENCE</span><h1>Lagoon House</h1></div><button className="close-menu iconbutton" onClick={()=>setMenu(false)} aria-label="Close navigation"><X/></button></div>
   <p className="site-meta">30 × 40 ft <span/> North-facing plot</p>
   <div className="divider"/>
   <div className="section-heading">EXPLORE THE HOUSE</div>
   <button className={'floor-button '+(floor===-1?'selected':'')} onClick={()=>chooseFloor(-1)}><Buildings size={21}/><span>Whole house</span><span className="floor-num">ALL</span></button>
   {FLOORS.map((name,i)=><button key={name} className={'floor-button '+(floor===i?'selected':'')} onClick={()=>chooseFloor(i)}><Stack size={21} weight={floor===i?'duotone':'regular'}/><span>{name}</span><span className="floor-num">0{i}</span></button>)}
   <div className="floor-options"><label><span>Hide upper floors</span><input type="checkbox" checked={isolated} onChange={e=>toggle(setIsolated,'setIsolated',e.target.checked)}/></label><label><span>Show roof</span><input type="checkbox" checked={roof} onChange={e=>toggle(setRoof,'setRoof',e.target.checked)}/></label></div>
   <div className="section-heading space-heading">SPACES <span>{floor<0?'ALL LEVELS':FLOORS[floor].toUpperCase()}</span></div>
   <nav className="rooms" aria-label="Room navigation">{ROOMS.filter(r=>floor===-1||r.floor===floor).map(r=><button className={room?.id===r.id?'room-button active':'room-button'} key={r.id} onClick={()=>chooseRoom(r)}><span>{r.name}</span><CaretRight size={14}/></button>)}</nav>
   <div className="sidebar-footer"><button onClick={()=>setInfo(true)}><Info size={18}/> Design notes & controls</button><span>Architectural concept · September 2026</span></div>
  </aside>
  <header className="topbar"><div className="view-label"><span className="eyebrow">{floor<0?'THE COMPLETE RESIDENCE':`LEVEL 0${floor}`}</span><h2>{room?.name||(floor<0?'A home around water':floor===0?'Arrival & lagoon':floor===1?'Living & gathering':floor===2?'Private family floor':'Suite & terrace')}</h2></div><div className="top-actions"><div className="segmented"><button className={!night?'on':''} onClick={()=>toggle(setNight,'setNight',false)} aria-label="Day mode"><Sun size={18}/><span>Day</span></button><button className={night?'on':''} onClick={()=>toggle(setNight,'setNight',true)} aria-label="Night mode"><Moon size={18}/><span>Night</span></button></div><button className="iconbutton capture" aria-label="Save current view as image" title="Save image" onClick={()=>engine.current?.screenshot()}><Camera size={20}/></button><button className="iconbutton" aria-label="Fullscreen" title="Fullscreen" onClick={()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.()}><ArrowsOut size={20}/></button></div></header>
  {room&&<div className="room-caption"><span className="eyebrow">{FLOORS[room.floor]} FLOOR</span><h3>{room.name}</h3><p>{room.note}</p><button aria-label="Dismiss room description" onClick={()=>setRoom(null)}><X size={16}/></button></div>}
  <div className="compass" title="North is toward the road"><Compass size={33} weight="thin"/><span>N</span></div>
  <footer className="bottombar"><div className="segmented mode"><button className={!walk?'on':''} onClick={()=>toggle(setWalk,'setWalk',false)}><Cube size={19}/>Orbit</button><button className={walk?'on':''} onClick={()=>toggle(setWalk,'setWalk',true)}><PersonSimpleWalk size={19}/>Walk</button></div><div className="view-controls"><button className={'tour-button '+(tour?'playing':'')} onClick={()=>{setTour(!tour);engine.current?.tour(!tour);}}>{tour?<Pause size={17} weight="fill"/>:<Play size={17} weight="fill"/>}<span>{tour?'Pause tour':'Camera tour'}</span></button><label className="view-select"><Eye size={18}/><select aria-label="Architectural camera preset" value={view} onChange={e=>chooseView(e.target.value)}>{VIEWS.map((v,i)=><option key={v.id+i} value={v.id}>{v.name}</option>)}</select></label></div><button className="iconbutton" title="Reset view" aria-label="Reset view" onClick={()=>chooseFloor(-1)}><ArrowCounterClockwise size={20}/></button></footer>
  <div className="hint">{walk?'Drag to look · WASD / arrows to move · Use floor buttons for level access':'Drag to orbit · Scroll to zoom · Right-drag to pan'}</div>
  <div className="quality"><select value={quality} aria-label="Rendering quality" onChange={e=>toggle(setQuality,'setQuality',e.target.value)}><option value="high">High detail</option><option value="balanced">Balanced</option></select><span>{stats.fps?stats.fps+' fps':'…'}</span></div>
  {walk&&<div className="walk-pad" aria-label="Touch walking controls">{[['KeyW',ArrowUp,'Forward'],['KeyA',ArrowLeft,'Left'],['KeyS',ArrowDown,'Back'],['KeyD',ArrowRight,'Right']].map(([key,Icon,label])=><button key={key} aria-label={label} onPointerDown={e=>keyButton(e,key,true)} onPointerUp={e=>keyButton(e,key,false)} onPointerCancel={e=>keyButton(e,key,false)}><Icon size={23}/></button>)}</div>}
  {info&&<div className="modal-scrim" onClick={()=>setInfo(false)}><section className="notes" role="dialog" aria-modal="true" aria-label="Design notes" onClick={e=>e.stopPropagation()}><button className="iconbutton close" onClick={()=>setInfo(false)} aria-label="Close design notes"><X size={22}/></button><span className="eyebrow">LAGOON HOUSE / CONCEPT 01</span><h2>Designed around arrival.</h2><p>A compact tropical home with a landscaped ground floor, a sculptural stair atrium and four bedrooms across three residential levels.</p><h3>Explore</h3><p><strong>Orbit</strong> for exterior and cutaway views. Choose a floor to remove the floors above it. Choose a room to move inside. <strong>Walk</strong> uses WASD or the on-screen arrows; drag to look. Change levels using the floor selector or room list. The lift is modelled; its cabin is not animated.</p><h3>Scale & planning</h3><p>The site is 9.144 × 12.192 m. Floor-to-floor height is 3.30 m. Each curved stair has 20 rises of 165 mm and a 1.20 m clear width. The two parking bays are each 2.60 × 5.20 m; a third car is omitted to protect the garden.</p><h3>Vastu intent & trade-offs</h3><p>North road, east-facing residential door, north-east puja and water, and south-west master suite. The stair sits in the south/south-east to preserve the master suite and west parking. The show kitchen occupies the east side; the separate wet kitchen is south-west. This is a disclosed compromise, not a claim of complete Vastu compliance.</p><h3>Before construction</h3><p>This is a navigable design concept, not a sanctioned or construction-ready plan. Setbacks, permitted floors, structural spans, fire escape, pool drainage/barriers, accessibility and detailed service routes require a local architect and engineers. The shell assumes nearly the full plot; mandatory setbacks may require significant replanning.</p><h3>Performance</h3><p>Balanced mode lowers pixel density, shadow resolution and selected planting. Lagoon and stair tessellation remain unchanged. Geometry is batched by material; hidden upper levels are culled.</p><button className="primary" onClick={()=>setInfo(false)}>Back to the house</button></section></div>}
 </main>
}
