import React,{useEffect,useRef,useState} from 'react';
import {Compass,Sun,Moon,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,ArrowsOut,Camera,Stack,PersonSimpleWalk,Cube,Play,Pause,X,List,Info,Leaf,ArrowCounterClockwise,CaretRight,Eye,Buildings,Blueprint} from '@phosphor-icons/react';
import {ROOMS,VIEWS,FLOORS} from './plan.js';
import {SITE,LEVELS,measure} from './layout.js';
import {FloorPlan} from './FloorPlan.jsx';
import './styles.css';
export function App(){
 const mount=useRef(null),engine=useRef(null),pending=useRef(null);
 const [mode,setMode]=useState('plan'),[ready,setReady]=useState(false),[error,setError]=useState(''),[floor,setFloor]=useState(1),[unit,setUnit]=useState('m'),[night,setNight]=useState(false),[walk,setWalk]=useState(false),[isolated,setIsolated]=useState(true),[roof,setRoof]=useState(true),[cutaway,setCutaway]=useState(true),[people,setPeople]=useState(true),[quality,setQuality]=useState('high'),[room,setRoom]=useState(null),[view,setView]=useState('aerial'),[menu,setMenu]=useState(false),[info,setInfo]=useState(false),[tour,setTour]=useState(false),[stats,setStats]=useState({fps:0}),[showFurniture,setShowFurniture]=useState(true),[showDimensions,setShowDimensions]=useState(true),[labels,setLabels]=useState(false);
 useEffect(()=>{let cancelled=false;if(mode==='plan'){engine.current?.setActive(false);return;}if(engine.current){engine.current.setActive(true);return;}if(error)return;
  import('./engine.js').then(({createEngine})=>{if(cancelled)return;try{const e=createEngine(mount.current,()=>setReady(true),setStats,f=>{setFloor(f);setCutaway(false);});engine.current=e;e.setNight(night);e.setQuality(quality);e.setIsolated(isolated);e.setRoof(roof);e.setPeople(people);e.setDimensions(labels,unit);e.setFloor(floor);if(pending.current){e.goTo(pending.current,!!pending.current.bounds);pending.current=null;}}catch(err){console.error(err);setError('This browser could not open the 3D model. Enable hardware acceleration or use a browser with WebGL support. The measured 2D plans remain available.');}});return()=>{cancelled=true;};
 },[mode]);
 useEffect(()=>()=>engine.current?.dispose(),[]);
 function chooseFloor(f){setFloor(f);setRoom(null);setTour(false);setWalk(false);setCutaway(f>=0);pending.current=null;engine.current?.tour(false);engine.current?.setWalk(false);engine.current?.setFloor(f);if(f<0)setMode('model');setMenu(false);}
 function chooseRoom(r,open3D=false){if(!r)return;setRoom(r);setFloor(r.floor);setTour(false);engine.current?.tour(false);engine.current?.selectRoom(r);if(mode==='model'||open3D){setCutaway(false);pending.current=r;if(engine.current){engine.current.goTo(r,true);pending.current=null;}setMode('model');}setMenu(false);}
 function changeMode(value){if(value==='plan'){if(floor<0){setFloor(1);engine.current?.setFloor(1);}setWalk(false);setTour(false);engine.current?.setWalk(false);engine.current?.tour(false);}else{pending.current=room;if(engine.current&&room)engine.current.goTo(room,true);}setMode(value);}
 function chooseView(id){const v=VIEWS.find(v=>v.id===id);if(!v)return;setView(id);setTour(false);const activeRoom=v.bounds?(ROOMS.find(r=>r.id===v.id.replace(/^view-/,''))||v):null;setRoom(activeRoom);setCutaway(false);setFloor(v.floor??-1);if(v.night){setNight(true);engine.current?.setNight(true);}engine.current?.setFloor(v.floor??-1,false);engine.current?.setCutaway(false);engine.current?.goTo(activeRoom||v,!!activeRoom);}
 const toggle=(setter,fn,value)=>{setter(value);engine.current?.[fn](value);};
 function changeUnit(v){setUnit(v);engine.current?.setDimensions(labels,v);}
 function keyButton(e,key,v){e.preventDefault();engine.current?.setKey(key,v);if(v)e.currentTarget.setPointerCapture(e.pointerId);}
 const model=mode==='model';
 return <main className={'app '+(model?'model-mode':'plan-mode')+(night&&model?' night':'')}>
  <section ref={mount} className="viewport" style={{display:model?'block':'none'}} aria-label="Villa 3D viewport" />
  <button className="mobile-menu iconbutton" aria-label="Open floor and room navigation" onClick={()=>setMenu(!menu)}><List size={22}/></button>
  {menu&&<button className="menu-shade" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}
  <aside className={'sidebar '+(menu?'open':'')}>
   <div className="brand"><span className="brandmark"><Leaf size={29} weight="thin"/></span><div><span className="eyebrow">PRIVATE RESIDENCE</span><h1>Lagoon House</h1></div><button className="close-menu iconbutton" onClick={()=>setMenu(false)} aria-label="Close navigation"><X/></button></div>
   <p className="site-meta">30 × 40 ft <span/> North road</p><div className="divider"/>
   <div className="section-heading">EXPLORE THE HOUSE</div>
   <button className={'floor-button '+(floor===-1?'selected':'')} onClick={()=>chooseFloor(-1)}><Buildings size={21}/><span>Whole house in 3D</span><span className="floor-num">ALL</span></button>
   {FLOORS.map((name,i)=><button key={name} className={'floor-button '+(floor===i?'selected':'')} onClick={()=>chooseFloor(i)}><Stack size={21} weight={floor===i?'duotone':'regular'}/><span>{name}</span><span className="floor-num">0{i}</span></button>)}
   {model?<div className="floor-options"><label>Hide upper floors<input type="checkbox" checked={isolated} onChange={e=>toggle(setIsolated,'setIsolated',e.target.checked)}/></label><label>Cutaway walls<input type="checkbox" checked={cutaway} onChange={e=>toggle(setCutaway,'setCutaway',e.target.checked)}/></label><label>Show roof<input type="checkbox" checked={roof} onChange={e=>toggle(setRoof,'setRoof',e.target.checked)}/></label><label>Dimension labels<input type="checkbox" checked={labels} onChange={e=>{setLabels(e.target.checked);engine.current?.setDimensions(e.target.checked,unit);}}/></label><label>1.70 m scale figure<input type="checkbox" checked={people} onChange={e=>toggle(setPeople,'setPeople',e.target.checked)}/></label></div>:<div className="scale-card"><Blueprint size={20}/><p><strong>Drawn at real scale</strong><span>9.144 × 12.192 m boundary<br/>Rooms measured inside walls</span></p></div>}
   <div className="section-heading space-heading">SPACES <span>{floor<0?'ALL LEVELS':`LEVEL 0${floor}`}</span></div>
   <nav className="rooms" aria-label="Room navigation">{ROOMS.filter(r=>floor===-1||r.floor===floor).map(r=><button className={room?.id===r.id?'room-button active':'room-button'} key={r.id} onClick={()=>chooseRoom(r)}><span>{r.name}</span><CaretRight size={14}/></button>)}</nav>
   <div className="sidebar-footer"><button onClick={()=>setInfo(true)}><Info size={18}/> Design notes & controls</button><span>Measured concept · Revision 02</span></div>
  </aside>
  <header className="topbar"><div className="view-label"><span className="eyebrow">{floor<0?'THE COMPLETE RESIDENCE':`LEVEL 0${floor} / ${model?'3D EXPLORATION':'MEASURED DRAWING'}`}</span><h2>{room?.name||(floor<0?'A home around water':LEVELS[floor].title)}</h2></div><div className="top-actions"><div className="segmented representation" aria-label="Drawing or model"><button className={!model?'on':''} aria-pressed={!model} onClick={()=>changeMode('plan')}><Blueprint size={18}/>2D plan</button><button className={model?'on':''} aria-pressed={model} onClick={()=>changeMode('model')}><Cube size={18}/>3D model</button></div><select className="unit-select" aria-label="Dimension units" value={unit} onChange={e=>changeUnit(e.target.value)}><option value="m">Metres</option><option value="ft">Feet / inches</option></select><button className="iconbutton fullscreen" aria-label="Fullscreen" onClick={()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.()}><ArrowsOut size={20}/></button></div></header>
  {!model&&<FloorPlan floor={floor<0?1:floor} unit={unit} selected={room} onSelect={chooseRoom} on3D={r=>chooseRoom(r,true)} showFurniture={showFurniture} setShowFurniture={setShowFurniture} showDimensions={showDimensions} setShowDimensions={setShowDimensions}/>}
  {model&&(!ready||error)&&<div className="loading" role="status"><Cube size={38} weight="thin"/><h2>{error?'3D needs WebGL':'Opening the model'}</h2><p>{error||'Preparing the measured architecture, interiors and water…'}</p>{error&&<button className="primary" onClick={()=>changeMode('plan')}>Return to 2D plans</button>}</div>}
  {model&&ready&&!error&&<>
   <div className="model-tools"><div className="segmented"><button className={!night?'on':''} onClick={()=>toggle(setNight,'setNight',false)} aria-label="Day mode"><Sun size={18}/>Day</button><button className={night?'on':''} onClick={()=>toggle(setNight,'setNight',true)} aria-label="Night mode"><Moon size={18}/>Night</button></div><button className="iconbutton capture" aria-label="Save current 3D view as image" onClick={()=>engine.current?.screenshot()}><Camera size={20}/></button><span className="scale-badge">{walk||room?`Eye level ${SITE.eyeHeight.toFixed(2)} m`:'1 world unit = 1 metre'} · 50° lens</span></div>
   {room&&<div className="room-caption"><span className="eyebrow">{FLOORS[room.floor]} FLOOR</span><h3>{room.name}</h3><strong>{measure(room,unit)} · {room.area.toFixed(2)} m²</strong><p>{room.note}</p><button aria-label="Dismiss room description" onClick={()=>{setRoom(null);engine.current?.selectRoom(null);}}><X size={16}/></button></div>}
   <div className="compass" title="North is toward the road"><Compass size={33} weight="thin"/><span>N</span></div>
   <footer className="bottombar"><div className="segmented mode"><button className={!walk?'on':''} onClick={()=>toggle(setWalk,'setWalk',false)}><Cube size={19}/>Orbit</button><button className={walk?'on':''} onClick={()=>{setCutaway(false);toggle(setWalk,'setWalk',true);}}><PersonSimpleWalk size={19}/>Walk</button></div><div className="view-controls"><button className={'tour-button '+(tour?'playing':'')} onClick={()=>{setTour(!tour);setWalk(false);setRoom(null);setCutaway(false);engine.current?.setWalk(false);engine.current?.tour(!tour);}}>{tour?<Pause size={17} weight="fill"/>:<Play size={17} weight="fill"/>}<span>{tour?'Pause tour':'Camera tour'}</span></button><label className="view-select"><Eye size={18}/><select aria-label="Architectural camera preset" value={view} onChange={e=>chooseView(e.target.value)}>{VIEWS.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label></div><button className="iconbutton" aria-label="Reset view" onClick={()=>chooseFloor(-1)}><ArrowCounterClockwise size={20}/></button></footer>
   <div className="hint">{walk?'Drag to look · WASD to move · Change levels with the floor selector':'Drag to orbit · Scroll to zoom · Select a room for an eye-level view'}</div>
   <div className="quality"><select value={quality} aria-label="Rendering quality" onChange={e=>toggle(setQuality,'setQuality',e.target.value)}><option value="high">High detail</option><option value="balanced">Balanced</option></select><span>{stats.fps?stats.fps+' fps':'…'}</span></div>
   {walk&&<div className="walk-pad" aria-label="Touch walking controls">{[['KeyW',ArrowUp,'Forward'],['KeyA',ArrowLeft,'Left'],['KeyS',ArrowDown,'Back'],['KeyD',ArrowRight,'Right']].map(([key,Icon,label])=><button key={key} aria-label={label} onPointerDown={e=>keyButton(e,key,true)} onPointerUp={e=>keyButton(e,key,false)} onPointerCancel={e=>keyButton(e,key,false)}><Icon size={23}/></button>)}</div>}
  </>}
  {info&&<div className="modal-scrim" onClick={()=>setInfo(false)}><section className="notes" role="dialog" aria-modal="true" aria-label="Design notes" onClick={e=>e.stopPropagation()}><button className="iconbutton close" onClick={()=>setInfo(false)} aria-label="Close design notes"><X size={22}/></button><span className="eyebrow">LAGOON HOUSE / REVISION 02</span><h2>Understand the space.</h2><p>The 2D drawings and 3D model share one set of room boundaries, partitions, openings and furniture coordinates. Dimensions are clear internal sizes; plot and building dimensions are outside sizes. The lagoon and living room use their actual irregular areas.</p><h3>The revised entrance stair</h3><p>Two straight flights, a 1.20 m corner landing, flared first steps, a sculpted underside and slim glass rails. Each storey has 20 rises of 165 mm, 290 mm treads and a 1.20 m nominal flight width. The atrium footprint is 3.81 × 3.81 m.</p><h3>Judge spaciousness honestly</h3><p>One metre in the plan equals one metre in 3D. Eye-level views are 1.65 m high with a fixed 50° vertical field of view. Cars, mattresses, counters and furniture retain actual sizes. The optional person is 1.70 m tall. Camera perspective changes with your screen; use the drawing dimensions as the reference.</p><h3>Explore</h3><p>Choose a level and select a room in its drawing or schedule. “See this space in 3D” opens its eye-level view. Selecting a floor gives a cutaway. Selecting a room restores full walls and the ceiling. Walk uses WASD or touch arrows; levels change with the floor selector. Stair climbing and lift motion are not simulated.</p><h3>Planning trade-offs</h3><p>The 6.15 m² main kitchen has no island. The wet kitchen has a 1.01 m aisle. The 2.85 m-wide master sleeping room is compact; its walk-in and bathroom are separate. Four dining places are comfortable; six are close. The guest uses a common bathroom. The north-east water/puja and south-west master follow the brief; the south-west wet kitchen is a Vastu compromise.</p><h3>Site assumptions</h3><p>The site is 9.144 × 12.192 m; the building envelope is 8.50 × 10.96 m. Side margins are only 0.322 m and front/rear margins 0.616 m. These are illustrative, not approved setbacks. Local approvals and structural, fire, drainage and accessibility design may require replanning. This is an architectural concept, not construction documentation.</p><h3>Performance</h3><p>Balanced mode adjusts texture filtering, planting, pixel density and shadows. It keeps the complete lagoon shoreline and staircase geometry. Hidden upper floors are culled, and 3D rendering pauses while you study a 2D plan.</p><button className="primary" onClick={()=>setInfo(false)}>Back to the house</button></section></div>}
 </main>;
}
