import React,{useMemo} from 'react';
import {DownloadSimple,Cube} from '@phosphor-icons/react';
import {floorSvg} from './plan-svg.js';
import {LEVELS,dims,measure,SITE} from './layout.js';
import {ROOMS} from './plan.js';
export function FloorPlan({floor,unit,selected,onSelect,on3D,showFurniture,setShowFurniture,showDimensions,setShowDimensions}){
 const f=Math.max(0,floor);const svg=useMemo(()=>floorSvg(f,{unit,selected:selected?.id,showFurniture,showDimensions}),[f,unit,selected,showFurniture,showDimensions]);
 function save(){const a=document.createElement('a');a.download=`Lagoon-House-Level-${f}-${unit}.svg`;a.href=URL.createObjectURL(new Blob([floorSvg(f,{unit,selected:selected?.id,showFurniture,showDimensions,includeSchedule:true})],{type:'image/svg+xml'}));a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 function pick(e){const el=e.target.closest('[data-room]');if(el)onSelect(ROOMS.find(r=>r.id===el.dataset.room&&r.floor===f));}
 return <section className="plan-workspace" aria-label="Dimensioned floor plan"><div className="plan-actions"><div><strong>{LEVELS[f].title}</strong><span>Same dimensions in the plan and model</span></div><div className="plan-checks"><label><input type="checkbox" checked={showFurniture} onChange={e=>setShowFurniture(e.target.checked)}/>Furniture</label><label><input type="checkbox" checked={showDimensions} onChange={e=>setShowDimensions(e.target.checked)}/>Dimensions</label><button onClick={save}><DownloadSimple size={18}/>Save plan</button></div></div><div className="plan-content"><div className="drawing" onClick={pick} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick(e);}}} dangerouslySetInnerHTML={{__html:svg}}/><aside className="schedule"><span className="eyebrow">CLEAR ROOM DIMENSIONS</span><p className="schedule-intro">Select a space to highlight it. Room sizes are inside wall faces. Lift and atrium sizes are overall footprints. Irregular spaces show bounding sizes and actual areas.</p><div className="schedule-head"><span>SPACE</span><span>SIZE / AREA</span></div>{LEVELS[f].rooms.map((r,i)=>{const d=dims(r);return <button key={r.id} onClick={()=>onSelect(ROOMS.find(q=>q.id===r.id&&q.floor===f))} className={'schedule-row '+(selected?.id===r.id?'active':'')}><span className="schedule-name"><b>{i+1}</b>{r.name}</span><span><strong>{measure(r,unit)}</strong><small>{d.area.toFixed(2)} m² · {(d.area*10.76391).toFixed(1)} ft²{r.polygon?' · irregular':r.kind==='stair'||r.kind==='lift'?' · footprint':''}</small></span></button>})}{selected&&<div className="space-detail"><h3>{selected.name}</h3><p>{selected.note}</p><p>Floor height: {SITE.floorHeight.toFixed(2)} m<br/>Clear ceiling: {SITE.ceiling.toFixed(2)} m</p><button onClick={()=>on3D(selected)}><Cube size={18}/>See this space in 3D</button></div>}<div className="plan-note"><strong>Read this at real scale</strong><p>Living + dining on Level 01: {(dims(LEVELS[1].rooms.find(r=>r.id==='living')).area+dims(LEVELS[1].rooms.find(r=>r.id==='dining')).area).toFixed(2)} m² combined, connected by an open edge. The wet kitchen and guest room are compact; the dimensions make that visible.</p></div></aside></div></section>;
}
