import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {loadCampus} from './campus-loader.js';
import {workers,workerPosition,vehicles,vehicleState,cameras,drones,permits,zones,alerts} from './domain.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config={},saved={},selected=null,elapsed=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,current='live',ready=false;
const records=new Map(),layers={worker:true,camera:true,drone:true,vehicle:true,permit:true,zone:true,alert:true};
const toast=s=>{const n=$('#toast');n.textContent=s;n.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.hidden=true,5000);};
const titles={live:'Situational awareness',explore:'Explore the plant',events:'Event register',reports:'Shift reports',personnel:'Personnel safety',cameras:'Video surveillance',vehicles:'Vehicle intelligence',permits:'Permit to work'};
function route(name){current=titles[name]?name:'live';history.replaceState(null,'','#'+current);$('#route-title').textContent=titles[current];$$('[data-route]').forEach(b=>{b.classList.toggle('active',b.dataset.route===current);b.setAttribute('aria-current',b.dataset.route===current?'page':'false');});$('#register').hidden=current==='live';document.body.classList.toggle('compact',current!=='live'&&current!=='explore');$('#search').value='';renderRegister();requestAnimationFrame(resize);}
$$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));window.addEventListener('hashchange',()=>route(location.hash.slice(1)));$('#search').oninput=renderRegister;
function table(headers,rows){return '<table><thead><tr>'+headers.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table>';}
const locate=(kind,id)=>`<button data-select="${kind}:${id}" aria-label="Locate ${id}">${kind==='worker'?id:'Locate'} ↗</button>`;
function renderRegister(){const q=$('#search').value.toLowerCase(),match=x=>JSON.stringify(x).toLowerCase().includes(q);$('#register-title').textContent=titles[current];let html='';
 if(current==='personnel')html=table(['Worker','Role','Area','Action'],workers.filter(match).map(w=>`<tr><td>${w.id}</td><td>${w.role}</td><td>${zones[w.zone][0]}</td><td>${locate('worker',w.id)}</td></tr>`));
 if(current==='vehicles')html=table(['Vehicle','Driver','IVMS state','Action'],vehicles.filter(match).map(v=>`<tr><td>${v.id} · ${v.name}</td><td>${v.driver}</td><td>${v.id==='VEH-006'?'Seatbelt warning':'Within speed limit'}</td><td>${locate('vehicle',v.id)}</td></tr>`));
 if(current==='permits')html=table(['Permit','Type / owner','Status','Action'],permits.filter(match).map(p=>`<tr><td>${p.id}</td><td>${p.type}<br>${p.owner}</td><td>${p.status}</td><td>${locate('permit',p.id)}</td></tr>`));
 if(current==='events')html=table(['Event','Severity','Status','Action'],alerts.filter(match).map(a=>`<tr><td>${a.id}<br>${a.title}</td><td>${a.severity}</td><td>${saved[a.id]?'Acknowledged':'Needs review'}</td><td><button data-alert="${a.id}">Locate event ↗</button></td></tr>`));
 if(current==='cameras')html='<div class="cards">'+[...cameras,...drones].filter(match).map(c=>`<article class="card"><b>${c.id}</b><span>${zones[c.zone][0]}</span><span>${c.online===false?'Offline':(config.cameraVideos?.[c.id]||config.droneVideos?.[c.id])?'Recorded footage configured':'No footage configured'}</span><button data-feed="${c.id}">Open feed</button> ${locate(c.id.startsWith('DRN')?'drone':'camera',c.id)}</article>`).join('')+'</div>';
 if(current==='explore')html='<div class="cards">'+zones.map((z,i)=>({name:z[0],i})).filter(match).map(z=>`<article class="card"><b>${z.name}</b><span>Illustrative operating area</span>${locate('zone','Z0'+(z.i+1))}</article>`).join('')+'</div>';
 if(current==='reports')html=`<div class="cards"><article class="card"><b>Current shift snapshot</b><span>248 personnel · 8 vehicles · 3 permits</span><span>${alerts.filter(a=>!saved[a.id]).length} unacknowledged events</span><button id="export-report">Download CSV</button></article><article class="card"><b>Data provenance</b><span>Synthetic telemetry and permits. Prerecorded camera and drone footage. No live plant integrations.</span></article><article class="card"><b>Model coverage</b><span>6 EPS-1 process areas. Original plant geometry with refined metallic surfaces and service-lane vehicles.</span></article></div>`;
 $('#records').innerHTML=html||'<p>No records match your filter.</p>';wireActions($('#records'));$('#export-report')?.addEventListener('click',()=>{const rows=[['Type','ID','Status'],...alerts.map(a=>['Alert',a.id,saved[a.id]?'Acknowledged':'Needs review']),...permits.map(p=>['Permit',p.id,p.status]),...vehicles.map(v=>['Vehicle',v.id,v.id==='VEH-006'?'Seatbelt warning':'Normal'])];const url=URL.createObjectURL(new Blob([rows.map(r=>r.map(c=>'"'+String(c).replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='signal-atlas-demo-shift.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
}
function wireActions(root){root.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{const [kind,id]=b.dataset.select.split(':');select(kind,id);});root.querySelectorAll('[data-feed]').forEach(b=>b.onclick=()=>openFeed(b.dataset.feed));root.querySelectorAll('[data-alert]').forEach(b=>b.onclick=()=>openAlert(b.dataset.alert));}
function renderAlerts(){$('#active-count').textContent=String(alerts.filter(a=>!saved[a.id]).length).padStart(2,'0');$('#alert-total').textContent=alerts.filter(a=>!saved[a.id]).length;$('#alert-list').innerHTML=alerts.filter(a=>!saved[a.id]).map(a=>`<button class="alert-item ${a.severity}" data-alert="${a.id}"><b>${a.title}</b><small>${a.id} · ${a.target}</small><em>${a.severity.toUpperCase()} · Locate in 3D ↗</em></button>`).join('')||'<p>All demo events acknowledged.</p>';wireActions($('#alert-list'));}
function openAlert(id){const a=alerts.find(a=>a.id===id);if(!a)return;route('live');select(a.kind,a.target,a);}
const host=$('#viewport'),scene=new T.Scene();scene.background=new T.Color(0x142432);scene.fog=new T.Fog(0x142432,350,900);
let renderer;try{renderer=new T.WebGLRenderer({antialias:true});}catch(error){$('#loading').textContent='3D requires WebGL. Enable browser hardware acceleration or use a compatible browser.';throw error;}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;host.prepend(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','3D plant. Drag to orbit; use arrow keys to rotate, plus or minus to zoom. Select individual workers through the People register.');
const camera=new T.PerspectiveCamera(43,1,.1,1500);camera.position.set(145,150,185);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,5,0);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.48;controls.minDistance=12;controls.maxDistance=650;
const hemi=new T.HemisphereLight(0xd4ebff,0x5c6450,2);scene.add(hemi);const sun=new T.DirectionalLight(0xffe7c9,3);sun.position.set(-70,160,85);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-220,right:220,top:150,bottom:-150,near:1,far:400});sun.shadow.bias=-.0004;sun.shadow.normalBias=.1;scene.add(sun);const rim=new T.DirectionalLight(0x83baff,1.5);rim.position.set(100,50,-100);scene.add(rim);
// Procedural reflection environment: geometry and light, no photographic backdrop.
const envScene=new T.Scene();envScene.background=new T.Color(0x263945);for(const [x,y,z,c] of [[-15,12,0,0xffffff],[15,9,0,0x7398b3],[0,16,-8,0xffecd4]]){const lightCard=new T.Mesh(new T.PlaneGeometry(12,12),new T.MeshBasicMaterial({color:c,side:T.DoubleSide}));lightCard.position.set(x,y,z);lightCard.lookAt(0,0,0);envScene.add(lightCard);}const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(envScene,.08).texture;
const waterGeo=new T.PlaneGeometry(1500,1500,160,160);waterGeo.rotateX(-Math.PI/2);const waterMaterial=new T.MeshPhysicalMaterial({color:0x071b26,metalness:.58,roughness:.28,clearcoat:1,clearcoatRoughness:.18});
// Analytic ripples affect the surface normals; no image backdrop or tiled photographs.
waterMaterial.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <normal_fragment_begin>','#include <normal_fragment_begin>\n normal = normalize(normal + vec3(sin(vViewPosition.x * 2.1) * .035, cos(vViewPosition.y * 1.7) * .035, 0.0));');};
const water=new T.Mesh(waterGeo,waterMaterial);water.position.y=-4.8;scene.add(water);
for(const [x,z] of [[-65,-65],[65,-65],[-65,65],[65,65]]){const lamp=new T.PointLight(0xffd899,140,45,2);lamp.position.set(x,8,z);scene.add(lamp);}
let campus;const items=new T.Group();scene.add(items);const pickables=[],pins=[];
const material=(c,m=.2)=>new T.MeshStandardMaterial({color:c,metalness:m,roughness:.5});const m={green:material(0x42cfaf),helmet:material(0xf0bf57),dark:material(0x182c39),steel:material(0xc0d2d7,.65),glass:material(0x335f79,.6),blue:material(0x5085e9)};
function part(parent,geo,mat,x,y,z){const o=new T.Mesh(geo,mat);o.position.set(x,y,z);o.castShadow=true;parent.add(o);return o;}
function register(kind,data,object){const rec={kind,data,object};records.set(kind+':'+data.id,rec);object.traverse(o=>{if(o.isMesh){o.userData.key=kind+':'+data.id;pickables.push(o);}});return rec;}
function pin(rec,text){const b=document.createElement('button');b.className=rec.kind;b.textContent=text;b.title=rec.data.id;b.setAttribute('aria-label',rec.data.id+' · '+rec.kind);b.onclick=()=>select(rec.kind,rec.data.id);$('#pins').append(b);pins.push({rec,node:b});}
function buildEntities(){
 for(const w of workers){const g=new T.Group();items.add(g);const body=part(g,new T.CylinderGeometry(.23,.3,.78,7),m.green,0,1.05,0);part(g,new T.SphereGeometry(.22,8,6),m.helmet,0,1.65,0);const legs=[];for(const x of [-.13,.13])legs.push(part(g,new T.BoxGeometry(.14,.7,.17),m.dark,x,.4,0));for(const x of [-.35,.35])part(g,new T.BoxGeometry(.12,.65,.15),m.green,x,1,0);const r=register('worker',w,g);r.legs=legs;}
 for(const v of vehicles){const g=new T.Group();items.add(g);part(g,new T.BoxGeometry(2.5,.55,8),m.dark,0,.8,0);part(g,new T.BoxGeometry(2.5,2.3,2.1),v.id==='VEH-006'?m.blue:m.green,0,2,3.2);part(g,new T.BoxGeometry(2.3,.8,.06),m.glass,0,2.65,4.28);if(v.name==='Road tanker'){const tank=part(g,new T.CylinderGeometry(1.25,1.25,5.3,18),m.steel,0,2,0);tank.rotation.x=Math.PI/2;for(const z of [-2.65,2.65])part(g,new T.SphereGeometry(1.25,14,10),m.steel,0,2,z).scale.z=.35;}else part(g,new T.BoxGeometry(2.3,1.7,4.9),m.steel,0,1.9,0);for(const x of [-1.25,1.25])for(const z of [-2.6,-1.4,3]){const wheel=part(g,new T.CylinderGeometry(.52,.52,.3,12),m.dark,x,.6,z);wheel.rotation.z=Math.PI/2;}pin(register('vehicle',v,g),v.id);}
 for(const c of cameras){const g=new T.Group();g.position.set(c.x,0,c.z);items.add(g);part(g,new T.CylinderGeometry(.07,.1,5.5,6),m.dark,0,2.75,0);part(g,new T.BoxGeometry(.7,.35,.4),m.steel,0,5.5,0);pin(register('camera',c,g),c.id.slice(-3));}
 for(const d of drones){const g=new T.Group();g.position.set(d.x,d.y,d.z);items.add(g);part(g,new T.BoxGeometry(1.6,.4,.8),m.dark,0,0,0);for(const x of [-1,1])for(const z of [-1,1]){const arm=part(g,new T.BoxGeometry(1.5,.09,.09),m.steel,x*.55,0,z*.55);arm.rotation.y=-Math.atan2(z,x);part(g,new T.CylinderGeometry(.6,.6,.04,12),m.dark,x,.2,z);}part(g,new T.SphereGeometry(.22,8,6),m.glass,0,-.3,0);pin(register('drone',d,g),'✦ '+d.id);}
 for(const p of permits){const g=new T.Group();g.position.set(p.x,.15,p.z);items.add(g);const ring=part(g,new T.RingGeometry(3.7,4,40),new T.MeshBasicMaterial({color:p.status==='Active'?0xf1bd64:0xff7887,side:T.DoubleSide}),0,0,0);ring.rotation.x=-Math.PI/2;pin(register('permit',p,g),p.id);}
 zones.forEach((z,i)=>{const g=new T.Group();g.position.set(z[1],1,z[2]+20);items.add(g);pin(register('zone',{id:'Z0'+(i+1),zone:i,name:z[0]},g),z[0].toUpperCase());});
 for(const a of alerts){const target=records.get(a.kind+':'+a.target);const rec={kind:'alert',data:a,object:target.object};pin(rec,'▲ '+a.id);const button=pins.at(-1).node;button.style.borderColor=a.severity==='critical'?'#ff7887':'#efbd69';button.onclick=()=>openAlert(a.id);}
}
function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h||!renderer)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(host);
let flight=null;function fly(pos,distance=55){const dir=camera.position.clone().sub(controls.target).normalize();dir.y=Math.max(.6,dir.y);dir.normalize();flight={start:performance.now(),from:camera.position.clone(),target:controls.target.clone(),to:pos.clone().addScaledVector(dir,distance),at:pos.clone()};}
controls.addEventListener('start',()=>flight=null);
renderer.domElement.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(event.key))return;event.preventDefault();flight=null;const delta=camera.position.clone().sub(controls.target),s=new T.Spherical().setFromVector3(delta);if(event.key==='ArrowLeft')s.theta-=.1;if(event.key==='ArrowRight')s.theta+=.1;if(event.key==='ArrowUp')s.phi-=.1;if(event.key==='ArrowDown')s.phi+=.1;if(event.key==='+'||event.key==='=')s.radius*=.9;if(event.key==='-')s.radius*=1.1;s.phi=T.MathUtils.clamp(s.phi,.05,Math.PI*.48);s.radius=T.MathUtils.clamp(s.radius,12,650);camera.position.copy(controls.target).add(new T.Vector3().setFromSpherical(s));});
const marker=new T.Mesh(new T.RingGeometry(1.7,2,36),new T.MeshBasicMaterial({color:0x48ffe0,side:T.DoubleSide}));marker.rotation.x=-Math.PI/2;marker.visible=false;scene.add(marker);
function select(kind,id,alert=null){if(!ready){toast('The 3D model is still loading. Please try again shortly.');return;}const r=records.get(kind+':'+id);if(!r)return;if(current!=='live')route('live');$('#viewport').scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});layers[kind]=true;const input=$('[data-layer="'+kind+'"]');if(input)input.checked=true;selected={...r,alert};fly(r.object.position,kind==='zone'?95:kind==='permit'?45:kind==='worker'?26:50);marker.visible=true;renderSelection();if(kind==='camera'||kind==='drone')openFeed(id);}
function kv(values){return '<div class="kpi-grid">'+values.map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('')+'</div>';}
function renderSelection(){if(!selected)return;const {kind,data:d,alert}=selected;let html=`<p class="eyebrow">${kind.toUpperCase()} / SIMULATED DATA</p><h2>${d.id}</h2>`;
 if(kind==='worker'){html+=`<p>${d.role} · ${zones[d.zone][0]}</p><div id="vitals">Loading smartwatch KPIs…</div><p class="status">${d.id==='P-042'?'SOS requires review':'Wearable connected · demo'}</p>`;}
 if(kind==='vehicle'){html+=`<p>${d.name} · ${d.driver}</p><div id="ivms"></div><p class="hint">Route and values are simulated—not a live IVMS connection.</p>`;}
 if(kind==='permit')html+=`<p>${d.type} · ${zones[d.zone][0]}</p><p class="status ${d.status==='Suspended'?'warning':''}">${d.status} · ${d.expires}</p><p>${d.owner}</p><ul class="detail-list">${d.controls.map(c=>'<li>'+c+'</li>').join('')}</ul><p>Assigned workers</p><div class="detail-actions">${d.workers.map(id=>locate('worker',id)).join('')}</div><p class="hint">Visualization only. This demo does not authorize work or validate isolation.</p>`;
 if(kind==='camera'||kind==='drone')html+=`<p>${zones[d.zone][0]}</p><p class="status">${d.online===false?'Offline':'Demonstration feed location'}</p><button data-feed="${d.id}">Open feed</button>`;
 if(kind==='zone')html+=`<p>${d.name}</p><p>Illustrative equipment placement. Local model coordinates, not surveyed geolocation.</p>`;
 if(alert)html+=`<hr><p class="eyebrow">${alert.severity.toUpperCase()} / ${alert.id}</p><h2>${alert.title}</h2><button id="ack" ${saved[alert.id]?'disabled':''}>${saved[alert.id]?'Acknowledged':'Acknowledge event'}</button>`;
 html+='<div class="detail-actions" style="margin-top:16px"><button id="refocus">Focus selection</button><button id="clear-selection">Clear</button></div>';$('#selection').innerHTML=html;wireActions($('#selection'));$('#refocus').onclick=()=>fly(selected.object.position,45);$('#clear-selection').onclick=()=>{selected=null;marker.visible=false;$('#selection').innerHTML='<p class="eyebrow">SITE INTELLIGENCE</p><h2>Select an asset</h2><p>Click a worker, vehicle, permit, camera or drone on the plant.</p>';};$('#ack')?.addEventListener('click',async()=>{try{const r=await fetch('/api/alerts/'+alert.id+'/acknowledge',{method:'POST'});if(!r.ok)throw Error();saved[alert.id]=true;renderAlerts();renderRegister();renderSelection();toast('Acknowledgment saved. This does not resolve the incident.');}catch{toast('Acknowledgment could not be saved. Check the backend connection.');}});if(kind==='worker')updateVitals();updateIVMS();}
async function updateVitals(){if(selected?.kind!=='worker')return;const id=selected.data.id;try{const r=await fetch('/api/personnel/'+id+'/vitals');if(!r.ok)throw Error();const v=await r.json();if(selected?.data.id!==id)return;$('#vitals').innerHTML=kv([['Pulse',v.heartRate+' bpm'],['Skin temperature',v.skinTemperature+' °C'],['SpO₂',v.spo2+'%'],['Stress index',v.stress],['Watch battery',v.battery+'%'],['Steps',v.steps.toLocaleString()]]);}catch{if($('#vitals'))$('#vitals').textContent='Telemetry unavailable. Retrying…';}}
function updateIVMS(){if(selected?.kind!=='vehicle'||!$('#ivms'))return;const v=vehicleState(selected.data,elapsed);$('#ivms').innerHTML=kv([['Speed',v.speedKph+' km/h'],['Zone limit',v.limit+' km/h'],['Seatbelt',v.seatbelt?'Fastened':'WARNING'],['Fuel',v.fuel+'%'],['Engine',v.engine],['Harsh braking',v.harshBraking]])+`<p class="status ${v.seatbelt?'':'warning'}">${v.seatbelt?'Within limits':'Driver seatbelt unfastened'}</p>`;}
async function openFeed(id){const c=[...cameras,...drones].find(x=>x.id===id);if(!c)return;const video=$('#feed-video');video.pause();video.removeAttribute('src');video.load();$('#feed-title').textContent=id+' · '+zones[c.zone][0];$('#feed-status').textContent='Recorded demonstration footage · continuous loop, not a live plant stream.';const src=config.cameraVideos?.[id]||config.droneVideos?.[id];$('#play-feed').hidden=true;if(!$('#feed-dialog').open)$('#feed-dialog').showModal();if(c.online===false||!src){$('#feed-status').textContent=c.online===false?'Camera offline in this demonstration.':'No recorded footage is configured for this location. Use CAM-012, CAM-021, CAM-034 or DRN-001–003.';return;}video.src=src;video.controls=false;video.loop=true;video.muted=true;video.onerror=()=>{$('#feed-status').textContent='Footage could not load. Check the media file and browser codec support.';};try{await video.play();}catch{$('#play-feed').hidden=false;}}
$('#play-feed').onclick=()=>$('#feed-video').play().then(()=>$('#play-feed').hidden=true).catch(()=>toast('Playback is unavailable.'));$('#close-feed').onclick=()=>$('#feed-dialog').close();$('#feed-dialog').addEventListener('close',()=>{$('#feed-video').pause();$('#feed-video').removeAttribute('src');$('#feed-video').load();});
$('#home').onclick=()=>{flight={start:performance.now(),from:camera.position.clone(),target:controls.target.clone(),to:new T.Vector3(145,150,185),at:new T.Vector3(0,0,0)};};$('#top').onclick=()=>{flight={start:performance.now(),from:camera.position.clone(),target:controls.target.clone(),to:new T.Vector3(0,230,.1),at:new T.Vector3()};};let dusk=false;$('#motion').textContent=paused?'Resume motion':'Pause motion';$('#motion').setAttribute('aria-pressed',String(paused));$('#light').onclick=()=>{dusk=!dusk;sun.intensity=dusk?.65:3;hemi.intensity=dusk?.8:2;renderer.toneMappingExposure=dusk?1.45:1.25;scene.background.set(dusk?0x081520:0x142432);scene.fog.color.copy(scene.background);};$('#motion').onclick=()=>{paused=!paused;$('#motion').textContent=paused?'Resume motion':'Pause motion';$('#motion').setAttribute('aria-pressed',String(paused));};$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('.spatial').requestFullscreen?.().catch(()=>toast('Fullscreen is unavailable.'));
$$('[data-layer]').forEach(input=>input.onchange=()=>layers[input.dataset.layer]=input.checked);
let down;const ray=new T.Raycaster();renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);const hit=ray.intersectObjects(pickables.filter(o=>{const key=o.userData.key;return layers[key.split(':')[0]];}),false)[0];if(hit){const [kind,id]=hit.object.userData.key.split(':');select(kind,id);}});
let last=0,frameNum=0;const vec=new T.Vector3();function frame(now){requestAnimationFrame(frame);const dt=Math.min(.1,(now-last)/1000||0);last=now;if(!paused)elapsed+=dt;if(flight){const t=Math.min(1,(now-flight.start)/850),e=1-(1-t)**3;camera.position.lerpVectors(flight.from,flight.to,e);controls.target.lerpVectors(flight.target,flight.at,e);if(t===1)flight=null;}controls.update();for(const r of records.values()){r.object.visible=layers[r.kind];if(r.kind==='worker'){const p=workerPosition(r.data,elapsed);r.object.position.set(p.x,.2,p.z);r.object.rotation.y=p.heading;r.legs?.forEach((l,i)=>l.rotation.x=Math.sin(elapsed*4+r.data.offset+i*Math.PI)*.35*(r.data.speed?1:0));}if(r.kind==='vehicle'){const v=vehicleState(r.data,elapsed);r.object.position.set(v.x,.1,v.z);r.object.rotation.y=v.heading;}}
 if(++frameNum%3===0&&!paused){const p=waterGeo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,.20*Math.sin(x*.12+elapsed*.7)+.13*Math.cos(z*.16+elapsed*.9));}p.needsUpdate=true;waterGeo.computeVertexNormals();}
 if(selected){marker.position.copy(selected.object.position);marker.position.y=.25;marker.visible=layers[selected.kind];}camera.updateMatrixWorld();for(const p of pins){vec.copy(p.rec.object.position);vec.y+=p.rec.kind==='camera'?6:p.rec.kind==='vehicle'?4:2;vec.project(camera);p.node.hidden=!layers[p.rec.kind]||(p.rec.kind==='alert'&&!!saved[p.rec.data.id])||vec.z<-1||vec.z>1||Math.abs(vec.x)>1||Math.abs(vec.y)>1;if(p.rec.kind==='camera'&&camera.position.distanceTo(controls.target)>180){p.node.hidden=Number(p.rec.data.id.slice(-3))%3!==0;}if(!p.node.hidden){p.node.style.left=(vec.x+1)*host.clientWidth/2+'px';p.node.style.top=(1-vec.y)*host.clientHeight/2+'px';}}renderer.render(scene,camera);}
async function start(){try{const responses=await Promise.all([fetch('/api/config'),fetch('/api/state')]);if(responses.some(r=>!r.ok))throw Error('Backend unavailable');const [cfg,state]=await Promise.all(responses.map(r=>r.json()));config=cfg;saved=Object.fromEntries(state.alerts.filter(a=>a.ack).map(a=>[a.id,true]));campus=await loadCampus(config.modelUrl||'/models/campus.glb');scene.add(campus);buildEntities();ready=true;$('#loading').remove();$('#scene-state').textContent='Illustrative plant · geometry loaded';renderAlerts();route(location.hash.slice(1)||'live');resize();requestAnimationFrame(frame);setInterval(()=>{updateVitals();updateIVMS();$('#clock').textContent=new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'})+' UTC';},4000);setupAR();}catch(e){console.error(e);$('#loading').textContent='Unable to load the project: '+e.message+'. Start the included backend and reload.';}}
function setupAR(){let session,arRenderer,overlay;$('#ar-view').onclick=async()=>{if(!navigator.xr||!await navigator.xr.isSessionSupported('immersive-ar').catch(()=>false)){toast('AR requires HTTPS and a compatible WebXR Android phone/tablet. This browser cannot place the model in AR.');return;}try{session=await navigator.xr.requestSession('immersive-ar',{requiredFeatures:['hit-test'],optionalFeatures:['dom-overlay'],domOverlay:{root:document.body}});arRenderer=new T.WebGLRenderer({alpha:true,antialias:true});arRenderer.xr.enabled=true;arRenderer.xr.setReferenceSpaceType('local');arRenderer.domElement.className='ar-canvas';document.body.append(arRenderer.domElement);const arScene=new T.Scene();arScene.add(new T.HemisphereLight(0xffffff,0x555555,3));const arCamera=new T.PerspectiveCamera();const copy=campus.clone(true);copy.scale.setScalar(.003);copy.visible=false;arScene.add(copy);const reticle=new T.Mesh(new T.RingGeometry(.10,.13,24).rotateX(-Math.PI/2),new T.MeshBasicMaterial({color:0x43e4ca}));reticle.matrixAutoUpdate=false;reticle.visible=false;arScene.add(reticle);const reference=await session.requestReferenceSpace('local'),viewer=await session.requestReferenceSpace('viewer'),hit=await session.requestHitTestSource({space:viewer});overlay=document.createElement('div');overlay.innerHTML='<button id="ar-exit">Exit AR</button><p class="ar-note">Move slowly over a clear surface. Tap the placement ring to place the plant.</p>';document.body.append(overlay);$('#ar-exit').onclick=()=>session.end();session.addEventListener('select',()=>{if(reticle.visible&&!copy.visible){copy.position.setFromMatrixPosition(reticle.matrix);copy.visible=true;overlay.querySelector('p').textContent='Plant placed. Walk around it to inspect. Operational overlays remain in the desktop 3D view.';}});session.addEventListener('end',()=>{hit.cancel();arRenderer.setAnimationLoop(null);arRenderer.dispose();arRenderer.domElement.remove();overlay.remove();session=null;});await arRenderer.xr.setSession(session);arRenderer.setAnimationLoop((_,f)=>{if(f){const result=f.getHitTestResults(hit)[0];reticle.visible=!!result&&!copy.visible;if(result)reticle.matrix.fromArray(result.getPose(reference).transform.matrix);}arRenderer.render(arScene,arCamera);});}catch(e){session?.end();arRenderer?.domElement.remove();overlay?.remove();toast('AR could not start. Check camera permission and HTTPS.');}};}
start();
