import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
const upgradeStyles=document.createElement('link');upgradeStyles.rel='stylesheet';upgradeStyles.href='./upgrade.css';document.head.append(upgradeStyles);const motionStyles=document.createElement('link');motionStyles.rel='stylesheet';motionStyles.href='./motion-cleanup.css';document.head.append(motionStyles);
const el=id=>document.getElementById(id),host=el('twin-viewport'),labels=el('spatial-labels'),info=el('spatial-info');
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true});}catch(e){el('twin-loading').textContent='3D view requires WebGL. Enable hardware acceleration or open this site in a WebGL-capable browser.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0x0b1723,0);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;host.prepend(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Interactive 3D plant. Drag to orbit, scroll to zoom, right-drag to pan. Arrow keys rotate; plus and minus zoom. Camera and alert markers are keyboard accessible.');
const scene=new T.Scene();scene.fog=new T.FogExp2(0x0b1826,.0017);const camera=new T.PerspectiveCamera(42,1,.2,1200);camera.position.set(155,160,200);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,4,0);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=15;controls.maxDistance=420;controls.maxPolarAngle=Math.PI*.475;controls.enablePan=true;
scene.add(new T.HemisphereLight(0xb3e3ff,0x152933,2.1));const light=new T.DirectionalLight(0xd8f5ff,3.2);light.position.set(60,160,90);scene.add(light);const rim=new T.DirectionalLight(0x4298d8,1.3);rim.position.set(-100,40,-80);scene.add(rim);
const plant=new T.Group();scene.add(plant);const peopleGroup=new T.Group();scene.add(peopleGroup);const cameraGroup=new T.Group();scene.add(cameraGroup);const droneGroup=new T.Group();scene.add(droneGroup);const alertGroup=new T.Group();scene.add(alertGroup);
const mats={deck:new T.MeshStandardMaterial({color:0x253d4c,roughness:.86}),edge:new T.MeshStandardMaterial({color:0x416475,metalness:.6,roughness:.48}),steel:new T.MeshStandardMaterial({color:0x8da8b2,metalness:.55,roughness:.43}),dark:new T.MeshStandardMaterial({color:0x365366,metalness:.6,roughness:.5}),pipe:new T.MeshStandardMaterial({color:0x64a7b5,metalness:.7,roughness:.33}),yellow:new T.MeshStandardMaterial({color:0xe0b361,metalness:.3,roughness:.5}),building:new T.MeshStandardMaterial({color:0x415b6a,roughness:.7}),glass:new T.MeshStandardMaterial({color:0x214d65,metalness:.45,roughness:.2}),red:new T.MeshBasicMaterial({color:0xff5975}),green:new T.MeshStandardMaterial({color:0x57f2bb,emissive:0x125b42,emissiveIntensity:.4}),blue:new T.MeshBasicMaterial({color:0x66b5ff})};
function mesh(geo,mat,x,y,z,parent=plant){const m=new T.Mesh(geo,typeof mat==='string'?mats[mat]:mat);m.position.set(x,y,z);parent.add(m);return m;}
function box(x,y,z,w,h,d,mat='steel',parent=plant){return mesh(new T.BoxGeometry(w,h,d),mat,x,y,z,parent)}
function cyl(x,y,z,r,h,mat='steel',parent=plant,rt=r){return mesh(new T.CylinderGeometry(rt,r,h,20),mat,x,y,z,parent)}
function pipe(a,b,r=.3,mat='pipe',parent=plant){const start=new T.Vector3(...a),end=new T.Vector3(...b),v=end.clone().sub(start);const m=mesh(new T.CylinderGeometry(r,r,v.length(),8),mat,...start.clone().add(end).multiplyScalar(.5).toArray(),parent);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),v.normalize());return m;}
const centers=[[-57,-34],[0,-34],[57,-34],[-57,29],[0,29],[68,35]];

const grid=new T.GridHelper(440,88,0x2d5265,0x182f40);grid.position.y=-5;scene.add(grid);
// Low-detail context platforms sit beyond EPS-1. They make the spatial viewer read
// as a live offshore/industrial complex without competing with the selectable plant.
const contextSites=new T.Group();scene.add(contextSites);
function contextSite(x,z,scale=1){const pad=new T.Mesh(new T.CylinderGeometry(22*scale,24*scale,2,8),mats.deck);pad.position.set(x,-3,z);contextSites.add(pad);const tower=new T.Mesh(new T.CylinderGeometry(1.2*scale,1.8*scale,16*scale,10),mats.steel);tower.position.set(x+3*scale,6*scale,z-2*scale);contextSites.add(tower);for(const [dx,dz] of [[-8,-5],[8,-4],[-4,8],[9,8]]){const module=box(x+dx*scale,1.2*scale,z+dz*scale,7*scale,2.4*scale,5*scale,'dark',contextSites);module.rotation.y=(dx+dz)*.07;const beacon=new T.Mesh(new T.SphereGeometry(.45*scale,8,8),mats.green);beacon.position.set(x+dx*scale,3*scale,z+dz*scale);contextSites.add(beacon);}}
contextSite(-150,-86,.7);contextSite(153,83,.62);contextSite(-124,104,.48);
try { const loaded=await new T.ObjectLoader().loadAsync(window.SA_CONFIG.modelUrl);plant.add(loaded); } catch(e) {el('twin-loading').textContent='Unable to load the plant model. Check models/plant-model.json and backend/config.json.';throw e;}
const pins=[],camRecords=[],personRecords=[],eventRecords=[];const project=new T.Vector3();
function pin(type,id,pos,content,title){const node=document.createElement('button');node.className='spatial-pin '+(type==='alert'?'alert-pin':'');node.textContent=content;node.title=title;node.setAttribute('aria-label',title);labels.append(node);const rec={type,id,pos:pos.clone(),node};pins.push(rec);return rec;}
const zoneLabels=centers.map(([x,z],i)=>{const node=document.createElement('div');node.className='zone-label';node.textContent=window.saData.zones[i].name;labels.append(node);return{node,pos:new T.Vector3(x,1,z+25)}});
let seed=19;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const personGeo=new T.CylinderGeometry(.34,.45,1.2,6),headGeo=new T.SphereGeometry(.34,7,5);let personNum=0;const clickablePeople=[];
// Rejection-sampled positions create natural, non-overlapping worker clusters instead of a perimeter grid.
function scatteredWorkers(zone,count){
 const [cx,cz]=centers[zone],points=[],halfX=zone===5?22:20,halfZ=zone===2?17:18;let spacing=3.05,attempts=0;
 const processFootprints=[[[ -59,-35,13,10]],[[0,-34,12,8]],[[57,-34,13,8]],[[-57,29,10,8]],[[0,29,10,8]],[[68,35,11,8]]][zone];
 while(points.length<count&&attempts++<count*180){
  const x=cx+(rand()-.5)*halfX*2,z=cz+(rand()-.5)*halfZ*2;
  const edge=Math.abs(x-cx)/halfX+Math.abs(z-cz)/halfZ;
  const equipmentClearance=((x-cx)*(x-cx)+(z-cz)*(z-cz))<36&&(zone===1||zone===2||zone===4);
  const insideEquipment=processFootprints.some(([px,pz,w,d])=>Math.abs(x-px)<w&&Math.abs(z-pz)<d);
  if(edge>1.66||equipmentClearance||insideEquipment||points.some(p=>(p.x-x)**2+(p.z-z)**2<spacing**2))continue;
  points.push({x,z});if(attempts>count*90&&points.length<count)spacing=2.45;
 }
 while(points.length<count)points.push({x:cx+(rand()-.5)*halfX*1.8,z:cz+(rand()-.5)*halfZ*1.8});
 return points;
}
for(let zone=0;zone<6;zone++)for(const point of scatteredWorkers(zone,window.saData.zones[zone].people)){
 const n=personNum++,x=point.x,z=point.z,group=new T.Group();group.position.set(x,.7,z);group.rotation.y=rand()*Math.PI*2;peopleGroup.add(group);
 const body=mesh(personGeo,'green',0,.65,0,group);mesh(headGeo,'yellow',0,1.6,0,group);body.userData.person=n;clickablePeople.push(body);
 personRecords.push({id:'P-'+String(n+1).padStart(3,'0'),zone,group,base:new T.Vector3(x,.7,z),phase:rand()*6,speed:.42+rand()*.32,driftX:(rand()>.5?1:-1)*(1.05+rand()*.75),driftZ:(rand()>.5?1:-1)*(.85+rand()*.65)});
}
// All 48 camera positions are attached to the model; CAM-047/048 are offline.
let camNum=0;for(let zone=0;zone<6;zone++){const [cx,cz]=centers[zone],count=window.saData.zones[zone].cameras;for(let i=0;i<count;i++){const ang=i/count*Math.PI*2;const pos=new T.Vector3(cx+Math.cos(ang)*21,7,cz+Math.sin(ang)*20);const target=new T.Vector3(cx,3,cz);const id='CAM-'+String(++camNum).padStart(3,'0');pipe([pos.x,0,pos.z],pos.toArray(),.12,'edge',cameraGroup);const device=box(pos.x,pos.y,pos.z,1.2,.6,.65,'dark',cameraGroup);device.lookAt(target);const p=pin('camera',id,pos.clone().add(new T.Vector3(0,2,0)),'▣',id+' · '+window.saData.zones[zone].name+(camNum>46?' · Offline':''));const rec={id,zone,pos,target,online:camNum<=46,pin:p};camRecords.push(rec);if(!rec.online){p.node.style.color='#e9b25a';p.node.style.borderColor='#8d6740';}p.node.onclick=()=>openCamera(rec);}}
const droneRecords=[];const droneSpecs=[{id:'DRN-001',zone:0,pos:[-63,23,-45]},{id:'DRN-002',zone:2,pos:[55,28,-8]},{id:'DRN-003',zone:4,pos:[4,26,49]}];
for(const spec of droneSpecs){const [x,y,z]=spec.pos,drone=new T.Group();drone.position.set(x,y,z);droneGroup.add(drone);const body=mesh(new T.BoxGeometry(3,.45,1.4),mats.dark,0,0,0,drone);body.castShadow=true;for(const sx of [-1.8,1.8])for(const sz of [-1.6,1.6]){const arm=mesh(new T.BoxGeometry(1.5,.12,.12),mats.edge,sx/2,.05,sz/2,drone);arm.rotation.y=Math.atan2(sz,sx);mesh(new T.CylinderGeometry(.62,.62,.08,16),mats.blue,sx,.2,sz,drone).rotation.x=Math.PI/2;}mesh(new T.SphereGeometry(.25,10,8),mats.green,0,-.25,.7,drone);const pinRec=pin('camera',spec.id,new T.Vector3(x,y+2,z),'✦',spec.id+' · Aerial drone feed · '+window.saData.zones[spec.zone].name);pinRec.node.classList.add('drone-tag');const rec={...spec,pos:new T.Vector3(x,y,z),group:drone,pin:pinRec,online:true};droneRecords.push(rec);pinRec.node.onclick=()=>openDrone(rec);}
const events=[{id:'SA-2041',pos:new T.Vector3(38,1,-28),label:'SOS · P-042',zone:2},{id:'SA-2040',pos:new T.Vector3(70,1,-14),label:'Restricted entry',zone:2},{id:'SA-2039',pos:new T.Vector3(-17,1,-22),label:'PPE warning',zone:1},{id:'SA-2038',pos:camRecords[46].pos.clone(),label:'CCTV offline',zone:5}];
for(const e of events){const a=window.saData.alerts.find(a=>a.id===e.id);const material=new T.MeshBasicMaterial({color:a.severity==='critical'?0xff5474:0xefb65b,transparent:true,opacity:.65,side:T.DoubleSide});const ring=mesh(new T.RingGeometry(2.6,3.1,40),material,e.pos.x,.25,e.pos.z,alertGroup);ring.rotation.x=-Math.PI/2;pipe([e.pos.x,.4,e.pos.z],[e.pos.x,11,e.pos.z],.07,a.severity==='critical'?'red':'yellow',alertGroup);const p=pin('alert',e.id,new T.Vector3(e.pos.x,13,e.pos.z),'▲ '+e.label,e.id+' · '+a.title);if(a.severity==='warning')p.node.classList.add('warning');p.node.onclick=()=>focusAlert(e.id);eventRecords.push({...e,pin:p,ring});}
// Locate the two named personnel precisely at their associated event coordinates.
const swapped=personRecords[64];swapped.base.copy(personRecords[41].base);swapped.group.position.copy(swapped.base);swapped.zone=personRecords[41].zone;
for(const [idx,eventIndex] of [[41,0],[86,1]]){const p=personRecords[idx],e=events[eventIndex];p.base.copy(e.pos);p.base.y=.7;p.group.position.copy(p.base);p.speed=0;p.zone=2;}
let selected=null,selectedCamera=null,flight=null,videoRenderer=null,stream=null,lastVideo=0,vitalsTimer=null;const cctvCamera=new T.PerspectiveCamera(64,16/9,.15,500);const selectionRing=mesh(new T.RingGeometry(2,2.3,40),new T.MeshBasicMaterial({color:0x8bd8ff,side:T.DoubleSide}),0,.3,0,scene);selectionRing.rotation.x=-Math.PI/2;selectionRing.visible=false;
function flyTo(pos,distance=70){const direction=camera.position.clone().sub(controls.target).normalize();direction.y=Math.max(direction.y,.45);direction.normalize();flight={fromPos:camera.position.clone(),fromTarget:controls.target.clone(),toTarget:pos.clone(),toPos:pos.clone().addScaledVector(direction,distance),start:performance.now()};}
function overview(){stopVitals();flight={fromPos:camera.position.clone(),fromTarget:controls.target.clone(),toTarget:new T.Vector3(0,4,0),toPos:new T.Vector3(155,160,200),start:performance.now()};selectionRing.visible=false;info.hidden=false;info.innerHTML='<span class="eyebrow">SITE OVERVIEW</span><strong>Spatial awareness, in context.</strong><p>Select a person, camera or alert directly on the plant.</p><div>248 personnel <b>·</b> 48 cameras <b>·</b> 4 events</div>';}
function nearby(pos){return camRecords.filter(c=>c.online).map(c=>({c,d:c.pos.distanceTo(pos)})).sort((a,b)=>a.d-b.d).slice(0,3)}
function cameraButtons(pos){return nearby(pos).map(({c,d})=>`<button class="near-cam" data-near="${c.id}"><span>▣ ${c.id} · View video</span><span>${Math.round(d)} m</span></button>`).join('')}
function stopVitals(){if(vitalsTimer){clearInterval(vitalsTimer);vitalsTimer=null;}}
function wireNearby(){info.querySelectorAll('[data-near]').forEach(b=>b.onclick=()=>openCamera(camRecords.find(c=>c.id===b.dataset.near)));info.querySelector('.info-dismiss')?.addEventListener('click',()=>{stopVitals();info.hidden=true})}
async function refreshVitals(id){try{const r=await fetch('/api/personnel/'+id+'/vitals');if(!r.ok)throw new Error();const v=await r.json();if(selected?.id!==id)return;const set=(name,value)=>{const node=info.querySelector('[data-vital="'+name+'"]');if(node)node.textContent=value;};set('heartRate',v.heartRate+' bpm');set('skinTemperature',v.skinTemperature+' °C');set('spo2',v.spo2+'%');set('stress',v.stress+' / 100');set('battery',v.battery+'%');set('steps',v.steps.toLocaleString());const status=info.querySelector('[data-vital="status"]');if(status){status.textContent=v.status;status.className=v.status==='Normal'?'vital-good':'vital-watch';}}catch{const node=info.querySelector('.vital-grid');if(node)node.classList.add('vitals-offline');}}
function selectPosition(pos){selectionRing.position.set(pos.x,.32,pos.z);selectionRing.visible=true;}
function focusAlert(id){const e=eventRecords.find(e=>e.id===id);if(!e)return;selected=e;const a=window.saData.alerts.find(a=>a.id===id);el('layer-alerts').checked=true;alertGroup.visible=true;info.hidden=false;flyTo(e.pos.clone().add(new T.Vector3(0,4,0)),70);selectPosition(e.pos);info.innerHTML=`<button class="info-dismiss" aria-label="Dismiss details">✕</button><span class="eyebrow ${a.severity==='critical'?'red':'amber'}">${id} · ${a.severity.toUpperCase()}</span><strong>${a.title}</strong><p>${window.saData.zones[e.zone].name}<br>X ${e.pos.x.toFixed(1)} · Y ${e.pos.y.toFixed(1)} · Z ${e.pos.z.toFixed(1)} m</p><div>Nearby online cameras · Spatial distance</div>${cameraButtons(e.pos)}<button class="ack-spatial" ${a.ack?'disabled':''}>${a.ack?'Acknowledged':'Acknowledge event'}</button><p style="font-size:10px;margin-bottom:0">Distance does not guarantee an unobstructed camera view.</p>`;wireNearby();info.querySelector('.ack-spatial').onclick=async()=>{await window.saAcknowledge(id);focusAlert(id)};}
function focusPerson(p){stopVitals();selected=p;info.hidden=false;flyTo(p.group.position,50);selectPosition(p.group.position);info.innerHTML=`<button class="info-dismiss" aria-label="Dismiss details">✕</button><span class="eyebrow">WEARABLE TELEMETRY · LIVE DEMO</span><strong>${p.id} · Field personnel</strong><p>${window.saData.zones[p.zone].name}<br>Smartwatch KPIs · updates every four seconds</p><div class="vital-grid"><span>Pulse <b data-vital="heartRate">—</b></span><span>Skin temp <b data-vital="skinTemperature">—</b></span><span>SpO₂ <b data-vital="spo2">—</b></span><span>Stress <b data-vital="stress">—</b></span><span>Battery <b data-vital="battery">—</b></span><span>Steps <b data-vital="steps">—</b></span></div><div class="wearable-state">Watch state <b data-vital="status">Sampling…</b></div><div>Nearby online cameras</div>${cameraButtons(p.group.position)}`;wireNearby();refreshVitals(p.id);vitalsTimer=setInterval(()=>refreshVitals(p.id),4000)}
function focusZone(index){const [x,z]=centers[index];flyTo(new T.Vector3(x,4,z),85);info.hidden=false;const zone=window.saData.zones[index];info.innerHTML=`<button class="info-dismiss" aria-label="Dismiss details">✕</button><span class="eyebrow">${zone.code}</span><strong>${zone.name}</strong><p>${zone.people} personnel · ${zone.cameras} cameras<br>Representative equipment layout</p><div>Nearby online cameras</div>${cameraButtons(new T.Vector3(x,0,z))}`;wireNearby()}
function closeVideo(){el('camera-dock').hidden=true;host.classList.remove('camera-open');const video=el('cctv-video');video.pause();video.controls=false;video.loop=true;video.srcObject=null;video.removeAttribute('src');video.onerror=null;video.load();if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}selectedCamera=null;}
const feedVideo=el('cctv-video');feedVideo.controls=false;feedVideo.loop=true;el('camera-time').remove();feedVideo.addEventListener('loadeddata',()=>{if(!selectedCamera||stream)return;const isDrone=selectedCamera.id.startsWith('DRN-');el('camera-title').textContent=selectedCamera.id+(isDrone?' · Aerial live feed':' · Live CCTV feed');el('camera-dock').querySelector('.eyebrow').textContent=isDrone?'LIVE DRONE FEED':'LIVE CCTV FEED';el('camera-dock').querySelector('.video-watermark').textContent=(isDrone?'AERIAL':'CCTV')+' LIVE FEED · '+selectedCamera.id;el('camera-message').textContent='Live feed view · recorded demonstration footage looping continuously.';});
function openCamera(c){closeVideo();selectedCamera=c;el('camera-dock').hidden=false;host.classList.add('camera-open');el('camera-title').textContent=c.id+' · '+(c.online?'Simulation':'Offline');el('camera-location').textContent=window.saData.zones[c.zone].name;el('camera-message').textContent='Generated from the 3D model at this camera position. No live VMS connection.';el('video-fallback').hidden=true;selectPosition(c.pos);el('camera-focus').onclick=()=>flyTo(c.pos,45);const configured=window.SA_CONFIG.cameraVideos?.[c.id];if(c.online&&configured){const video=el('cctv-video');video.src=configured;el('camera-dock').querySelector('.eyebrow').textContent='CONFIGURED VIDEO SOURCE';el('camera-dock').querySelector('.video-watermark').textContent='CONFIGURED VIDEO · '+c.id;el('camera-message').textContent='Playing the video source configured for '+c.id+'. Source freshness is not verified.';video.onerror=()=>{el('video-fallback').hidden=false;el('video-fallback').textContent='Video source unavailable or unsupported. Check its URL, file and browser codec support.';};video.play().catch(()=>{el('camera-message').textContent='Press Play to start the configured video.';});return;}el('camera-dock').querySelector('.eyebrow').textContent='SIMULATED CAMERA VIEW';el('camera-dock').querySelector('.video-watermark').textContent='3D SIMULATION · NOT LIVE CCTV';if(!c.online){el('video-fallback').hidden=false;el('video-fallback').textContent='Camera offline in this demonstration. Select a nearby online camera.';return;}cctvCamera.position.copy(c.pos);cctvCamera.lookAt(c.target);try{if(!videoRenderer){videoRenderer=new T.WebGLRenderer({antialias:true});videoRenderer.setSize(960,540);videoRenderer.outputColorSpace=T.SRGBColorSpace;videoRenderer.toneMapping=T.ACESFilmicToneMapping;videoRenderer.toneMappingExposure=1.65;videoRenderer.setClearColor(0x163047);}videoRenderer.render(scene,cctvCamera);if(typeof videoRenderer.domElement.captureStream!=='function')throw new Error('Video streaming is unsupported');stream=videoRenderer.domElement.captureStream(15);const video=el('cctv-video');video.srcObject=stream;video.play().catch(()=>{el('camera-message').textContent='Press Play to start the simulated camera stream.';});}catch(e){el('video-fallback').hidden=false;el('video-fallback').textContent='Video simulation is unavailable in this browser. The 3D camera location remains available.';}}
function openDrone(drone){closeVideo();selectedCamera=drone;el('camera-dock').hidden=false;host.classList.add('camera-open');el('camera-title').textContent=drone.id+' · Aerial surveillance';el('camera-location').textContent=window.saData.zones[drone.zone].name+' · Aerial route';el('camera-dock').querySelector('.eyebrow').textContent='CONFIGURED DRONE FEED';el('camera-dock').querySelector('.video-watermark').textContent='DRONE VIDEO · '+drone.id;el('video-fallback').hidden=true;selectPosition(drone.pos);el('camera-focus').onclick=()=>flyTo(drone.pos,45);const configured=window.SA_CONFIG.droneVideos?.[drone.id],video=el('cctv-video');if(!configured){el('video-fallback').hidden=false;el('video-fallback').textContent='No video is assigned to this drone.';return;}video.src=configured;el('camera-message').textContent='Playing the configured aerial footage for '+drone.id+'.';video.onerror=()=>{el('video-fallback').hidden=false;el('video-fallback').textContent='Drone video unavailable or unsupported by this browser.';};video.play().catch(()=>{el('camera-message').textContent='Press Play to start the configured drone footage.';});}
window.spatialFocusAlert=focusAlert;window.spatialFocusZone=focusZone;
function resize(){const w=host.clientWidth,h=host.clientHeight;if(w&&h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}}new ResizeObserver(resize).observe(host);window.spatialResize=()=>requestAnimationFrame(resize);resize();
el('home-view').onclick=overview;el('top-view').onclick=()=>{flight={fromPos:camera.position.clone(),fromTarget:controls.target.clone(),toTarget:new T.Vector3(0,0,0),toPos:new T.Vector3(0,250,.1),start:performance.now()}};el('full-view').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.querySelector('.plant-panel').requestFullscreen?.().catch(()=>{});};el('close-camera').onclick=closeVideo;
window.spatialLayerPreset=layer=>{el('layer-personnel').checked=layer!=='video';el('layer-cctv').checked=layer!=='people';el('layer-alerts').checked=layer==='safety';};
controls.addEventListener('start',()=>flight=null);let down=null;renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});const raycaster=new T.Raycaster();renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;const rect=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);if(el('layer-personnel').checked){const hits=raycaster.intersectObjects(clickablePeople,false);if(hits.length)focusPerson(personRecords[hits[0].object.userData.person]);}});
renderer.domElement.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key)){e.preventDefault();flight=null;const offset=camera.position.clone().sub(controls.target);if(e.key==='ArrowLeft'||e.key==='ArrowRight')offset.applyAxisAngle(new T.Vector3(0,1,0),e.key==='ArrowLeft'?.12:-.12);else if(e.key==='ArrowUp'||e.key==='ArrowDown'){const sph=new T.Spherical().setFromVector3(offset);sph.phi=T.MathUtils.clamp(sph.phi+(e.key==='ArrowUp'?-.1:.1),.08,Math.PI*.475);offset.setFromSpherical(sph)}else offset.multiplyScalar(e.key==='-'?1.1:.9);offset.clampLength(15,420);camera.position.copy(controls.target).add(offset);controls.update();}});
// Every visible worker mesh is directly selectable; no special personnel labels are needed.
el('twin-loading').remove();let last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function frame(now){requestAnimationFrame(frame);if(!host.clientWidth||!host.clientHeight)return;const t=now/1000;if(flight){const f=Math.min(1,(now-flight.start)/900),ease=1-Math.pow(1-f,3);camera.position.lerpVectors(flight.fromPos,flight.toPos,ease);controls.target.lerpVectors(flight.fromTarget,flight.toTarget,ease);if(f===1)flight=null;}controls.update();peopleGroup.visible=el('layer-personnel').checked;cameraGroup.visible=el('layer-cctv').checked;droneGroup.visible=el('layer-cctv').checked;alertGroup.visible=el('layer-alerts').checked;if(!reduced){for(const p of personRecords){const angle=t*p.speed+p.phase;p.group.position.x=p.base.x+Math.sin(angle)*p.driftX;p.group.position.z=p.base.z+Math.cos(angle*.8)*p.driftZ;p.group.rotation.y=Math.atan2(Math.cos(angle)*p.driftX,-Math.sin(angle*.8)*p.driftZ);}for(const d of droneRecords){d.group.position.y=d.pos.y;d.group.rotation.y+=.002;}}
for(const e of eventRecords){const pulse=reduced?1:1+Math.sin(t*2.5)*.13;e.ring.scale.set(pulse,pulse,1)}camera.updateMatrixWorld();
for(const p of pins){if(p.person)p.pos.copy(p.person.group.position).add(new T.Vector3(0,3,0));project.copy(p.pos).project(camera);const visible=project.z>-1&&project.z<1&&Math.abs(project.x)<1.08&&Math.abs(project.y)<1.08&&(p.type==='camera'?el('layer-cctv').checked:p.type==='alert'?el('layer-alerts').checked:el('layer-personnel').checked);p.node.hidden=!visible;if(visible){p.node.style.left=((project.x+1)*host.clientWidth/2)+'px';p.node.style.top=((-project.y+1)*host.clientHeight/2)+'px';p.node.style.zIndex=p.type==='alert'?4:p.type==='person'?3:1;}}
for(const z of zoneLabels){project.copy(z.pos).project(camera);z.node.hidden=!el('layer-labels').checked||project.z< -1||project.z>1;z.node.style.left=((project.x+1)*host.clientWidth/2)+'px';z.node.style.top=((-project.y+1)*host.clientHeight/2)+'px';}
renderer.render(scene,camera);if(selectedCamera?.online&&stream&&videoRenderer&&now-lastVideo>66){videoRenderer.render(scene,cctvCamera);lastVideo=now;}last=now;}
requestAnimationFrame(frame);
// Surveillance cards use the same actual model-mounted cameras.
document.querySelectorAll('[data-view="cameras"]').forEach(button=>button.addEventListener('click',()=>{setTimeout(()=>{const nodes=document.querySelectorAll('.camera-tile');const ids=['CAM-012','CAM-021','CAM-034','CAM-047'];nodes.forEach((node,i)=>{node.style.cursor='pointer';node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label','Open '+ids[i]+' on 3D site');const action=()=>{window.setView('overview');openCamera(camRecords.find(c=>c.id===ids[i]));};node.onclick=action;node.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();action()}};node.querySelector('.camera-placeholder').innerHTML='<span>▣</span>'+(i===3?'Offline · Locate on model':'Open spatial camera view ↗');});},0)}));
