// Shared deterministic demonstration model. Positions are local illustrative metres, not survey coordinates.
export const loop=[[-28,-58],[29,-58],[29,57],[-28,57]];
export function onPath(points,distance){const lengths=points.map((p,i)=>Math.hypot(p[0]-points[(i+1)%points.length][0],p[1]-points[(i+1)%points.length][1]));let d=((distance%lengths.reduce((a,b)=>a+b,0))+lengths.reduce((a,b)=>a+b,0))%lengths.reduce((a,b)=>a+b,0);for(let i=0;i<points.length;i++){if(d<=lengths[i]){const a=points[i],b=points[(i+1)%points.length],t=d/lengths[i];return{x:a[0]+(b[0]-a[0])*t,z:a[1]+(b[1]-a[1])*t,heading:Math.atan2(b[0]-a[0],b[1]-a[1])};}d-=lengths[i];}}
export const zones=[['Inlet facility',-57,-34],['Gas compression',0,-34],['Production separators',57,-34],['Utilities & power',-57,29],['Oil export & metering',0,29],['Wellhead towers',68,35]];
// Two offset pedestrian circuits per area, irregularly spaced starts. All bodies selectable.
export const workers=Array.from({length:248},(_,i)=>{const zone=i%6,[,x,z]=zones[zone],lane=Math.floor(i/6)%2;const w=19+lane*2,d=17+lane*2;const route=[[x-w,z-d],[x+w,z-d],[x+w,z+d],[x-w,z+d]];return{id:'P-'+String(i+1).padStart(3,'0'),zone,route,offset:Math.floor(i/12)*6.65+(zone*7.23)%5+Math.sin(Math.floor(i/12)*2.17)*.9,speed:.55,role:['Operator','Maintenance technician','Field engineer'][i%3]};});
export function workerPosition(w,time){return onPath(w.route,w.offset+time*w.speed);}
export const vehicles=Array.from({length:8},(_,i)=>({id:'VEH-'+String(i+1).padStart(3,'0'),name:i<5?'Road tanker':'Service vehicle',driver:'DRV-'+String(i+1).padStart(3,'0'),offset:i*43,speed:3,limit:20,route:loop}));
export function vehicleState(v,time){return{...v,...onPath(v.route,v.offset+time*v.speed),speedKph:10.8,seatbelt:v.id!=='VEH-006',fuel:64-Number(v.id.slice(-1))*3,engine:'Running',harshBraking:0,overspeed:false,mode:'simulated'};}
export const permits=[{id:'PTW-101',type:'Hot work',zone:1,x:18,z:-42,status:'Active',owner:'Maintenance team A',workers:['P-008','P-014'],controls:['Area isolated','Fire watch assigned','Gas test recorded'],expires:'End of demo shift'},{id:'PTW-102',type:'Confined space',zone:4,x:11,z:40,status:'Suspended',owner:'Inspection team',workers:['P-005','P-011'],controls:['Entry prohibited while suspended','Attendant required','Isolation verification required'],expires:'Pending revalidation'},{id:'PTW-103',type:'Electrical isolation',zone:3,x:-43,z:41,status:'Active',owner:'Electrical team',workers:['P-004','P-010'],controls:['LOTO recorded','Test before touch','Authorized personnel only'],expires:'End of demo shift'}];
export const cameras=Array.from({length:48},(_,i)=>{const zone=i%6,[,x,z]=zones[zone],edge=Math.floor(i/6);return{id:'CAM-'+String(i+1).padStart(3,'0'),zone,x:x+(edge%2?22:-22),z:z-20+Math.floor(edge/2)*13,online:i<46};});
export const drones=[{id:'DRN-001',x:-73,z:-20,y:36,zone:0},{id:'DRN-002',x:48,z:-18,y:43,zone:2},{id:'DRN-003',x:15,z:55,y:32,zone:4}];
export const alerts=[{id:'SA-2041',title:'Personnel SOS activated',severity:'critical',kind:'worker',target:'P-042'},{id:'SA-2040',title:'Permit zone requires review',severity:'critical',kind:'permit',target:'PTW-102'},{id:'SA-2039',title:'Driver seatbelt unfastened',severity:'warning',kind:'vehicle',target:'VEH-006'},{id:'SA-2038',title:'Camera connection lost',severity:'warning',kind:'camera',target:'CAM-047'}];
